source :rubygems

gem "rack-flash"
gem "sinatra"
gem "sinatra-content-for"
gem "sinatra-redirect-with-flash"
gem "sinatra-reloader"
gem "haml"
gem "sass"
gem "dm-core"
gem "dm-validations"
gem "dm-migrations"
gem "dm-timestamps"
gem "dm-serializer"
gem "dm-sqlite-adapter"
gem "dm-postgres-adapter"
gem "json"
